import { ref } from 'vue'

export type LanguageCode = 'en' | 'de'

const STORAGE_KEY = 'gt:language'

const messages: Record<LanguageCode, Record<string, string>> = {
  en: {
    language: 'Language',
    tabPlayerConfig: 'Bases',
    tabTechnology: 'Technology',
    tabConfig: 'Config',
    planetSearch: 'Search planet…',
    selectPlanet: 'Select planet…',
    addBase: 'Add base',
    alreadyAdded: '(already added)',
    delete: 'Delete',
    moveUp: 'Up',
    moveDown: 'Down',
    addBuilding: 'Add building…',
    building: 'Building',
    level: 'Level',
    count: 'Count',
    noResults: 'No results',
    editName: 'Edit name',
    save: 'Save',
    cancel: 'Cancel',
    buildingSearch: 'Search building…',
    recipeSearch: 'Search recipe…',
    requiresBuilding: 'Requires building',
    noRecipesConfigured: 'No recipes configured yet',
    dailySummary: 'Daily summary',
    summaryForHours: 'Summary for {hours}h',
    sectionProduction: 'Production',
    sectionBuildings: 'Buildings',
    totalRevenue: 'Total revenue',
    totalCosts: 'Total costs',
    productionRevenue: 'Production revenue',
    materialPurchaseCosts: 'Material purchases',
    workerPurchaseCosts: 'Worker consumables',
    netResult: 'Net result',
    adminCost: 'Administration cost',
    workerConsumption: 'Worker consumption',
    materialBalance: 'Materials balance',
    material: 'Material',
    perDay: 'per day',
    perHours: 'per {hours}h',
    unitPrice: 'Unit price',
    totalWorkerCosts: 'Total worker costs',
    workers: 'Workers',
    activeModules: 'Active modules',
    queueTimeShare: 'Queue time share',
    dailyRunsPerModule: 'Runs per module per day',
    runsPerHours: 'Runs per module per {hours}h',
    outputPerDay: 'Output per day',
    outputPerHours: 'Output per {hours}h',
    inputsPerDay: 'Inputs',
    inputsPerHours: 'Inputs per {hours}h',
    cycleTime: 'Cycle time',
    baseCycleTime: 'Base cycle',
    actualCycleTime: 'Effective cycle',
    minutes: 'minutes',
    workforcePenalty: 'Housing is insufficient – add accommodation to restore full output.',
    workforceOverview: 'Workforce coverage',
    requiredWorkers: 'Required',
    housingCapacity: 'Housing',
    coverage: 'Coverage',
    workforceDemand: 'Workforce demand',
    productivityFactor: 'Productivity bonus',
    abundanceFactor: 'Abundance factor',
    fertilityFactor: 'Fertility',
    abundanceZeroWarning: 'No abundance on this planet – production halted.',
    planetaryAbundance: 'Planetary abundance',
    requiresAbundance: 'Unavailable on this planet – no abundance.',
    requiresFertility: 'Unavailable – requires planetary fertility.',
    fertilityZeroWarning: 'No fertility on this planet – farming halted.',
    optionalHint: 'Optional consumables increase productivity. Toggle to apply them.',
    optionalActive: 'optional active',
    optionalInactive: 'optional inactive',
    priceLastUpdated: 'Prices updated',
    priceRefresh: 'Refresh prices',
    priceRefreshing: 'Refreshing…',
    nextRefreshIn: 'Next refresh in',
    priceError: 'Price fetch failed',
    gameDataTimestamp: 'Game data as of',
    workerTier1: 'Worker',
    workerTier2: 'Technician',
    workerTier3: 'Engineer',
    workerTier4: 'Scientist',
    reset: 'Reset',
    startingBonus: 'Starting bonus',
    technologyHeading: 'Technology levels',
    technologyStartingBonusTitle: 'Starting bonus',
    technologyStartingBonusHint: 'Applies multiplicatively to every production speed calculation.',
    technologyBonusDisplay: 'Effective modifier',
    technologyLevel: 'Tech-Level',
    technologyBonusLabel: 'Bonus',
    technologyConstruction: 'Construction',
    technologyConstructionDesc: 'Boosts construction-specialised buildings and recipes.',
    technologyManufacturing: 'Manufacturing',
    technologyManufacturingDesc: 'Boosts manufacturing-specialised buildings and recipes.',
    technologyAgriculture: 'Agriculture',
    technologyAgricultureDesc: 'Boosts agriculture-specialised buildings and recipes.',
    technologyResourceExtraction: 'Resource extraction',
    technologyResourceExtractionDesc: 'Boosts resource extraction-specialised buildings and recipes.',
    technologyMetallurgy: 'Metallurgy',
    technologyMetallurgyDesc: 'Boosts metallurgy-specialised buildings and recipes.',
    technologyChemistry: 'Chemistry',
    technologyChemistryDesc: 'Boosts chemistry-specialised buildings and recipes.',
    technologyElectronics: 'Electronics',
    technologyElectronicsDesc: 'Boosts electronics-specialised buildings and recipes.',
    technologyFoodProduction: 'Food production',
    technologyFoodProductionDesc: 'Boosts food production-specialised buildings and recipes.',
    technologyScience: 'Science',
    technologyScienceDesc: 'Boosts science-specialised buildings and recipes.',
    technologyRequirement: 'Requires technology level',
    technologyTooLow: 'Technology level too low',
    technologyBlockedWarning: 'Technology requirement not met – production halted.',
    stockImportTitle: 'Import stock',
    stockImportDescription: 'Paste your in-game stock export to estimate how long supplies will last.',
    stockImportPlaceholder: 'Paste stock data…',
    stockImportImported: 'Imported items',
    stockImportMissing: 'Not found',
    stockImportNoValid: 'No valid items found – please check the format.',
    stockImportError: 'Import failed – please check the format.',
    stockCoverage: 'Stock coverage',
    lessThanHour: '<1h',
    toBuy: 'To buy',
    timeframeHoursLabel: 'Summary window (hours)',
    timeframeHoursHint: 'Applies to all calculations (max 336h).',
    apiConfiguration: 'API Configuration',
    apiKeyLabel: 'API Key',
    apiKeyPlaceholder: 'Enter your API key from game settings',
    apiKeyHint: 'Your API key will be stored locally in your browser.',
    saveApiKey: 'Save API Key',
    apiKeySaved: 'API key saved',
    apiKeyNotConfigured: 'API key not configured. Please save your API key first.',
    apiKeySaveError: 'Failed to save API key.',
    worldLabel: 'World',
    worldG1: 'G1 (Test Server)',
    worldG2: 'G2 (Production)',
    worldHint: 'Select the server to use for API calls.',
    languageLabel: 'Language',
    apiSyncActions: 'Sync Actions',
    syncBases: 'Load my bases',
    syncWarehouse: 'Load warehouse stocks',
    basesLoadedSuccess: 'Loaded {count} bases from API',
    basesLoadError: 'Failed to load bases',
    warehouseStockLoadedSuccess: 'Warehouse stocks loaded successfully',
    warehouseStockLoadError: 'Failed to load warehouse stocks',
    lastWarehouseRefresh: 'Warehouse updated',
    importFromGame: 'Import from game',
    importFromGameShort: 'Import',
    importBaseConfirmTitle: 'Import base from game',
    importBaseConfirmMessage: 'This will overwrite all buildings and production orders for this base. Continue?',
    importBaseLoading: 'Importing…',
    importBaseSuccess: 'Base imported successfully',
    importBaseError: 'Import failed',
  },
  de: {
    language: 'Sprache',
    tabPlayerConfig: 'Basen',
    tabTechnology: 'Technologien',
    tabConfig: 'Einstellungen',
    planetSearch: 'Planet suchen…',
    selectPlanet: 'Planet wählen…',
    addBase: 'Basis hinzufügen',
    alreadyAdded: '(bereits hinzugefügt)',
    delete: 'Löschen',
    moveUp: 'Hoch',
    moveDown: 'Runter',
    addBuilding: 'Gebäude hinzufügen…',
    building: 'Gebäude',
    level: 'Level',
    count: 'Anzahl',
    noResults: 'Keine Treffer',
    editName: 'Name bearbeiten',
    save: 'Speichern',
    cancel: 'Abbrechen',
    buildingSearch: 'Gebäude suchen…',
    recipeSearch: 'Rezept suchen…',
    requiresBuilding: 'Benötigt Gebäude',
    noRecipesConfigured: 'Noch keine Rezepte konfiguriert',
    dailySummary: 'Tägliche Übersicht',
    summaryForHours: 'Übersicht für {hours}h',
    sectionProduction: 'Produktion',
    sectionBuildings: 'Gebäude',
    totalRevenue: 'Gesamterlös',
    totalCosts: 'Gesamtkosten',
    productionRevenue: 'Produktionserlöse',
    materialPurchaseCosts: 'Materialeinkäufe',
    workerPurchaseCosts: 'Verbrauchskosten Arbeiter',
    netResult: 'Nettoergebnis',
    adminCost: 'Verwaltungskosten',
    workerConsumption: 'Verbrauch der Arbeiter',
    materialBalance: 'Materialbilanz',
    material: 'Material',
    perDay: 'pro Tag',
    perHours: 'pro {hours}h',
    unitPrice: 'Preis',
    totalWorkerCosts: 'Summe Verbrauchskosten',
    workers: 'Arbeiter',
    activeModules: 'Aktive Module',
    queueTimeShare: 'Zeitanteil der Queue',
    dailyRunsPerModule: 'Durchgänge pro Tag',
    runsPerHours: 'Durchgänge pro Modul pro {hours}h',
    outputPerDay: 'Ausstoß pro Tag',
    outputPerHours: 'Ausstoß pro {hours}h',
    inputsPerDay: 'Input',
    inputsPerHours: 'Input pro {hours}h',
    cycleTime: 'Zykluszeit',
    baseCycleTime: 'Normaler Zyklus',
    actualCycleTime: 'Realer Zyklus',
    minutes: 'Minuten',
    workforcePenalty: 'Durch fehlenden Wohnraum gebremst – mehr Wohngebäude hinzufügen.',
    workforceOverview: 'Arbeitskräfte & Wohnraum',
    requiredWorkers: 'Benötigt',
    housingCapacity: 'Wohnraum',
    coverage: 'Abdeckung',
    workforceDemand: 'Arbeitskräftebedarf',
    productivityFactor: 'Produktivitätsbonus',
    abundanceFactor: 'Vorkommenfaktor',
    fertilityFactor: 'Fruchtbarkeit',
    abundanceZeroWarning: 'Kein Vorkommen auf diesem Planeten – Produktion gestoppt.',
    planetaryAbundance: 'Planeten-Vorkommen',
    requiresAbundance: 'Auf diesem Planeten nicht verfügbar – kein Vorkommen.',
    requiresFertility: 'Nicht verfügbar – Planet hat keine Fruchtbarkeit.',
    fertilityZeroWarning: 'Keine Fruchtbarkeit auf diesem Planeten – Produktion gestoppt.',
    optionalHint: 'Optionale Verbrauchsgüter steigern die Produktivität. Aktivieren zum Anwenden.',
    optionalActive: 'optional aktiv',
    optionalInactive: 'optional inaktiv',
    priceLastUpdated: 'Preise aktualisiert',
    priceRefresh: 'Preise aktualisieren',
    priceRefreshing: 'Aktualisiere…',
    nextRefreshIn: 'Nächste Aktualisierung in',
    priceError: 'Preisabruf fehlgeschlagen',
    gameDataTimestamp: 'Spieldaten Stand',
    workerTier1: 'Arbeiter',
    workerTier2: 'Techniker',
    workerTier3: 'Ingenieur',
    workerTier4: 'Wissenschaftler',
    reset: 'Zurücksetzen',
    startingBonus: 'Startbonus',
    technologyHeading: 'Technologiestufen',
    technologyStartingBonusTitle: 'Startbonus',
    technologyStartingBonusHint: 'Wirkt multiplikativ auf jede Produktionsgeschwindigkeit.',
    technologyBonusDisplay: 'Effektiver Modifikator',
    technologyLevel: 'Tech-Stufe',
    technologyBonusLabel: 'Bonus',
    technologyConstruction: 'Konstruktion',
    technologyConstructionDesc: 'Steigert Gebäude und Rezepte der Spezialisierung Konstruktion.',
    technologyManufacturing: 'Fertigung',
    technologyManufacturingDesc: 'Steigert Gebäude und Rezepte der Spezialisierung Fertigung.',
    technologyAgriculture: 'Landwirtschaft',
    technologyAgricultureDesc: 'Steigert Gebäude und Rezepte der Spezialisierung Landwirtschaft.',
    technologyResourceExtraction: 'Rohstoffabbau',
    technologyResourceExtractionDesc: 'Steigert Gebäude und Rezepte der Spezialisierung Rohstoffabbau.',
    technologyMetallurgy: 'Metallurgie',
    technologyMetallurgyDesc: 'Steigert Gebäude und Rezepte der Spezialisierung Metallurgie.',
    technologyChemistry: 'Chemie',
    technologyChemistryDesc: 'Steigert Gebäude und Rezepte der Spezialisierung Chemie.',
    technologyElectronics: 'Elektronik',
    technologyElectronicsDesc: 'Steigert Gebäude und Rezepte der Spezialisierung Elektronik.',
    technologyFoodProduction: 'Nahrungsproduktion',
    technologyFoodProductionDesc: 'Steigert Gebäude und Rezepte der Spezialisierung Nahrungsproduktion.',
    technologyScience: 'Wissenschaft',
    technologyScienceDesc: 'Steigert Gebäude und Rezepte der Spezialisierung Wissenschaft.',
    technologyRequirement: 'Benötigt Technologiestufe',
    technologyTooLow: 'Technologiestufe zu niedrig',
    technologyBlockedWarning: 'Technologievoraussetzung nicht erfüllt – Produktion gestoppt.',
    stockImportTitle: 'Lager importieren',
    stockImportDescription: 'Füge den Export aus dem Spiel ein, um die Reichweite deiner Vorräte zu berechnen.',
    stockImportPlaceholder: 'Lagerdaten einfügen…',
    stockImportImported: 'Importierte Einträge',
    stockImportMissing: 'Nicht gefunden',
    stockImportNoValid: 'Keine gültigen Einträge gefunden – bitte Format prüfen.',
    stockImportError: 'Import fehlgeschlagen – bitte Format prüfen.',
    stockCoverage: 'Reichweite Lager',
    lessThanHour: '<1h',
    toBuy: 'Zukauf',
    timeframeHoursLabel: 'Berechnungszeitraum (Stunden)',
    timeframeHoursHint: 'Gilt für alle Berechnungen (max. 336h).',
    apiConfiguration: 'API-Konfiguration',
    apiKeyLabel: 'API Schlüssel',
    apiKeyPlaceholder: 'API Schlüssel aus den Spieleinstellungen',
    apiKeyHint: 'Dein API Schlüssel wird lokal in deinem Browser gespeichert.',
    saveApiKey: 'API Schlüssel speichern',
    apiKeySaved: 'API Schlüssel gespeichert',
    apiKeyNotConfigured: 'API Schlüssel nicht konfiguriert. Bitte speichere deinen API Schlüssel.',
    apiKeySaveError: 'Fehler beim Speichern des API Schlüssels.',
    worldLabel: 'Welt',
    worldG1: 'G1 (Testserver)',
    worldG2: 'G2 (Produktion)',
    worldHint: 'Wähle den Server für API-Anfragen.',
    languageLabel: 'Sprache',
    apiSyncActions: 'Synchronisierungsaktionen',
    syncBases: 'Meine Basen laden',
    syncWarehouse: 'Lagerstände laden',
    basesLoadedSuccess: '{count} Basen aus API geladen',
    basesLoadError: 'Fehler beim Laden der Basen',
    warehouseStockLoadedSuccess: 'Lagerstände erfolgreich geladen',
    warehouseStockLoadError: 'Fehler beim Laden der Lagerstände',
    lastWarehouseRefresh: 'Lagerstand aktualisiert',
    importFromGame: 'Aus Spiel importieren',
    importFromGameShort: 'Importieren',
    importBaseConfirmTitle: 'Basis aus Spiel importieren',
    importBaseConfirmMessage: 'Dies überschreibt alle Gebäude und Produktionsaufträge dieser Basis. Fortfahren?',
    importBaseLoading: 'Importiere…',
    importBaseSuccess: 'Basis erfolgreich importiert',
    importBaseError: 'Import fehlgeschlagen',
  },
}

const currentLanguage = ref<LanguageCode>(detectInitial())
document.documentElement.lang = currentLanguage.value

function detectInitial(): LanguageCode {
  const saved = localStorage.getItem(STORAGE_KEY) as LanguageCode | null
  if (saved && messages[saved]) return saved
  
  // Default to English on first visit, regardless of browser language
  return 'en'
}

export function translate(
  key: string,
  vars?: Record<string, string | number>,
): string {
  const template = messages[currentLanguage.value]?.[key] ?? key
  if (!vars) return template
  return template.replace(/\{(\w+)\}/g, (_, token: string) => {
    const value = vars[token]
    return value == null ? '' : String(value)
  })
}

export function setLanguage(lang: LanguageCode): void {
  if (!messages[lang]) return
  currentLanguage.value = lang
  localStorage.setItem(STORAGE_KEY, lang)
  document.documentElement.lang = lang
}

export function getCurrentLanguage(): LanguageCode {
  return currentLanguage.value
}

export const availableLanguages: Array<{ code: LanguageCode; label: string }> = [
  { code: 'en', label: 'English' },
  { code: 'de', label: 'Deutsch' },
]
